SuperHeroes2/Models/ErrorViewModel.cs
using System;

namespace SuperHeroes2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperHeroes2/Models/SuperHero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperHeroes2.Models
{
    public class SuperHero
    {
        [Key]
        public int Id { get; set; }

       
        public string Name { get; set; }
        [Display (Name="Alter Ego")]
        public string AlterEgo { get; set; }
        [Display(Name = "Main Power")]
        public string MainPower { get; set; }
        [Display(Name = "Secondary Power")]
        public string SecondaryPower { get; set; }
        [Display(Name = "Catch Phrase")]

        public string CatchPhrase { get; set; }
    }
}

SuperHeroes2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperHeroes2.Models;

namespace SuperHeroes2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperHeroes2/Controllers/SuperHeroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperHeroes2.Data;
using SuperHeroes2.Models;

namespace SuperHeroes2.Controllers
{
    public class SuperHeroesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SuperHeroesController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: SuperHeroes
        public ActionResult Index()
        {
            var superHeroes = _db.SuperHeroes.ToList();

            return View(superHeroes);
        }

        // GET: SuperHeroes/Details/5
        public ActionResult Details(int id)
        {
            var superHero = _db.SuperHeroes.Where(q => q.Id == id).SingleOrDefault();
            return View(superHero);
        }

        // GET: SuperHeroes/Create
        public ActionResult Create()
        {
            SuperHero superHero = new SuperHero();
            return View(superHero);
        }

        // POST: SuperHeroes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SuperHero superHero)
        {
            try
            {
                // TODO: Add insert logic here
                _db.Add(superHero);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperHeroes/Edit/5
        public ActionResult Edit(int id)
        {
            SuperHero superHero = _db.SuperHeroes.Where(q => q.Id == id).FirstOrDefault();
            return View(superHero);
        }

        // POST: SuperHeroes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SuperHero superHero)
        {
            try
            {
                // TODO: Add update logic here
                SuperHero hero2Update = _db.SuperHeroes.Where(q => q.Id == id).FirstOrDefault();
                hero2Update.Name = superHero.Name;
                hero2Update.AlterEgo = superHero.AlterEgo;
                hero2Update.MainPower = superHero.MainPower;
                hero2Update.SecondaryPower = superHero.SecondaryPower;
                hero2Update.CatchPhrase = superHero.CatchPhrase;
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperHeroes/Delete/5
        public ActionResult Delete(int id)
        {
            SuperHero super = _db.SuperHeroes.Where(q => q.Id == id).FirstOrDefault();
            return View(super);
        }

        // POST: SuperHeroes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, SuperHero super)
        {
            try
            {
                // TODO: Add delete logic here
                var superHero = _db.SuperHeroes.Where(q => q.Id == id).FirstOrDefault();
                _db.Remove(superHero);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperHeroes2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">I've Been Expecting You Super Hero Friends</h1>
        @*</div>
    <br />
<div class="text-center">*@
        <img  src="~/Images/Heimdall.jpg" alt="Heimdall" width="500" />
    </div>

SuperHeroes2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Super Heroes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Super Heroes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="SuperHeroes" asp-action="Index">View Heroes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="SuperHeroes" asp-action="Create">Create Hero</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Super Heroes- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SuperHeroes2/Views/SuperHeroes/Create.cshtml
@model SuperHeroes2.Models.SuperHero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Super Hero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label">Alter Ego</label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainPower" class="control-label">Main Power</label>
                <input asp-for="MainPower" class="form-control" />
                <span asp-validation-for="MainPower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryPower" class="control-label">Secondary Power</label>
                <input asp-for="SecondaryPower" class="form-control" />
                <span asp-validation-for="SecondaryPower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label">Catch Phrase</label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperHeroes2/Views/SuperHeroes/Delete.cshtml
@model SuperHeroes2.Models.SuperHero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Hero</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Super Hero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainPower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainPower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryPower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryPower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperHeroes2/Views/SuperHeroes/Details.cshtml
@model SuperHeroes2.Models.SuperHero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SuperHero</h4>
    <hr />
    <dl class="row">
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainPower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainPower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryPower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryPower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
</div>
<div>
    <input type="hidden" asp-for="Id" />
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn bg-success btn-sm text-black-50">Edit</a>|
    <a asp-action="Index">Back to List</a>
</div>

SuperHeroes2/Views/SuperHeroes/Edit.cshtml
@model SuperHeroes2.Models.SuperHero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SuperHero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainPower" class="control-label"></label>
                <input asp-for="MainPower" class="form-control" />
                <span asp-validation-for="MainPower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryPower" class="control-label"></label>
                <input asp-for="SecondaryPower" class="form-control" />
                <span asp-validation-for="SecondaryPower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SuperHeroes2/Views/SuperHeroes/Index.cshtml
@model IEnumerable<SuperHeroes2.Models.SuperHero>

@{
    ViewData["Title"] = "Heroes";
}

    <h1>Heroes List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlterEgo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MainPower)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondaryPower)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatchPhrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlterEgo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MainPower)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondaryPower)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CatchPhrase)
            </td>
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>*@

                @*asp-route-id="@item.Id">Delete*@
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn bg-success btn-sm text-black-50">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>